"""add workflow tracking fields to workflow_runs

Revision ID: 1dadde69c8cc
Revises: ecb7cf5ee18e
Create Date: 2025-12-30 16:33:37.305018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dadde69c8cc'
down_revision: Union[str, Sequence[str], None] = 'ecb7cf5ee18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_embeddings_ivfflat', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.add_column(sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True))
        batch_op.add_column(sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
        batch_op.add_column(sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('run_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('event_payload', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_column('event_payload')
        batch_op.drop_column('run_url')
        batch_op.drop_column('author')
        batch_op.drop_column('commit_message')
        batch_op.drop_column('commit_sha')
        batch_op.drop_column('branch')
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_incidents_embeddings_ivfflat', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###
