"""add application logs table

Revision ID: 5cb5d7bc3422
Revises: d38d004f24bf
Create Date: 2025-12-28 00:04:55.898742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5cb5d7bc3422'
down_revision: Union[str, Sequence[str], None] = 'd38d004f24bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_logs',
    sa.Column('log_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('category', sa.Enum('WEBHOOK', 'LLM', 'ANALYSIS', 'REMEDIATION', 'GITHUB', 'DATABASE', 'SYSTEM', name='logcategory'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.create_index('idx_app_logs_category_created', ['category', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_app_logs_incident', ['incident_id'], unique=False)
        batch_op.create_index('idx_app_logs_level_created', ['level', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_app_logs_stage', ['stage'], unique=False)
        batch_op.create_index('idx_app_logs_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_logs_stage'))
        batch_op.drop_index(batch_op.f('ix_application_logs_level'))
        batch_op.drop_index(batch_op.f('ix_application_logs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_application_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_application_logs_category'))
        batch_op.drop_index('idx_app_logs_user')
        batch_op.drop_index('idx_app_logs_stage')
        batch_op.drop_index('idx_app_logs_level_created')
        batch_op.drop_index('idx_app_logs_incident')
        batch_op.drop_index('idx_app_logs_category_created')

    op.drop_table('application_logs')
    # ### end Alembic commands ###
