"""add webhook management fields

Revision ID: 9a0b7bb4241d
Revises: 1dadde69c8cc
Create Date: 2026-01-02 10:30:36.429268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a0b7bb4241d'
down_revision: Union[str, Sequence[str], None] = '1dadde69c8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_events', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('webhook_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('webhook_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('webhook_last_delivery_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('webhook_secret',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.alter_column('webhook_secret',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('webhook_last_delivery_at')
        batch_op.drop_column('webhook_created_at')
        batch_op.drop_column('webhook_status')
        batch_op.drop_column('webhook_events')

    # ### end Alembic commands ###
