"""migrate to zitadel

Revision ID: af00678c6efa
Revises: 9a0b7bb4241d
Create Date: 2026-01-18 20:48:51.261689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af00678c6efa'
down_revision: Union[str, Sequence[str], None] = '9a0b7bb4241d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sessions_expires'))
        batch_op.drop_index(batch_op.f('idx_sessions_user_active'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('oauth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('refresh_token_hash')
        batch_op.drop_column('is_mfa_enabled')
        batch_op.drop_column('token_version')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token_version', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('refresh_token_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('oauth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('user_sessions',
    sa.Column('session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device_fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('user_sessions_pkey'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_sessions_user_active'), ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_sessions_expires'), ['expires_at'], unique=False)

    # ### end Alembic commands ###
