"""add_oauth_and_repository_connection_tables

Revision ID: e09828c63ceb
Revises: eeb0d5dfeb54
Create Date: 2025-12-30 15:41:21.024579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e09828c63ceb'
down_revision: Union[str, Sequence[str], None] = 'eeb0d5dfeb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_connections', schema=None) as batch_op:
        batch_op.create_index('idx_oauth_provider_user', ['provider', 'provider_user_id'], unique=False)
        batch_op.create_index('idx_oauth_user_provider', ['user_id', 'provider'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_connections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_connections_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_connections_provider_user_id'), ['provider_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_connections_user_id'), ['user_id'], unique=False)

    op.create_table('repository_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('oauth_connection_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('repository_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('repository_full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repository_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('webhook_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_pr_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_fix_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('repository_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['oauth_connection_id'], ['oauth_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.create_index('idx_repo_oauth_enabled', ['oauth_connection_id', 'is_enabled'], unique=False)
        batch_op.create_index('idx_repo_user_full_name', ['user_id', 'repository_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_repository_connections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_connections_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_connections_oauth_connection_id'), ['oauth_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_connections_repository_full_name'), ['repository_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_connections_user_id'), ['user_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('repository_connection_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('workflow_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('conclusion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('run_attempt', sa.Integer(), nullable=True),
    sa.Column('head_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('head_sha', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['repository_connection_id'], ['repository_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index('idx_wfrun_incident', ['incident_id'], unique=False)
        batch_op.create_index('idx_wfrun_repo_run_id', ['repository_connection_id', 'run_id'], unique=True)
        batch_op.create_index('idx_wfrun_status', ['status', 'conclusion'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_repository_connection_id'), ['repository_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_repository_connection_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_incident_id'))
        batch_op.drop_index('idx_wfrun_status')
        batch_op.drop_index('idx_wfrun_repo_run_id')
        batch_op.drop_index('idx_wfrun_incident')

    op.drop_table('workflow_runs')
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_repository_connections_repository_full_name'))
        batch_op.drop_index(batch_op.f('ix_repository_connections_provider'))
        batch_op.drop_index(batch_op.f('ix_repository_connections_oauth_connection_id'))
        batch_op.drop_index(batch_op.f('ix_repository_connections_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_repository_connections_created_at'))
        batch_op.drop_index('idx_repo_user_full_name')
        batch_op.drop_index('idx_repo_oauth_enabled')

    op.drop_table('repository_connections')
    with op.batch_alter_table('oauth_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_connections_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_connections_provider'))
        batch_op.drop_index(batch_op.f('ix_oauth_connections_is_active'))
        batch_op.drop_index(batch_op.f('ix_oauth_connections_created_at'))
        batch_op.drop_index('idx_oauth_user_provider')
        batch_op.drop_index('idx_oauth_provider_user')

    op.drop_table('oauth_connections')
    # ### end Alembic commands ###
