"""add webhook_url to repository_connections

Revision ID: ecb7cf5ee18e
Revises: e09828c63ceb
Create Date: 2025-12-30 16:16:56.370298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecb7cf5ee18e'
down_revision: Union[str, Sequence[str], None] = 'e09828c63ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_connections', schema=None) as batch_op:
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
