"""add_background_jobs_table

Revision ID: eeb0d5dfeb54
Revises: 5cb5d7bc3422
Create Date: 2025-12-28 00:56:42.914762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eeb0d5dfeb54'
down_revision: Union[str, Sequence[str], None] = '5cb5d7bc3422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('job_type', sa.Enum('INCIDENT_ANALYSIS', 'INCIDENT_REANALYSIS', 'EXPORT_CSV', 'EXPORT_PDF', 'BULK_UPDATE', 'BULK_DELETE', 'PR_CREATION', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result_file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('result_file_size', sa.Integer(), nullable=True),
    sa.Column('result_file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_status_created', ['status', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_jobs_type_status', ['job_type', 'status'], unique=False)
        batch_op.create_index('idx_jobs_user_created', ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_completed_at'))
        batch_op.drop_index('idx_jobs_user_created')
        batch_op.drop_index('idx_jobs_type_status')
        batch_op.drop_index('idx_jobs_status_created')

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
